export const fieldsMap = {
  AccountType: "Acount Type",
  AdditionalField1: "Additional Field1",
  AdditionalField2: "Additional Field2",
  AdditionalField3: "Additional Field3",
  AdditionalField4: "Additional Field4",
  AdditionalField5: "Additional Field5",
  AltuomGUID: "Alt Unit GUID",
  AltuomName: "Alt Unit Name",
  AlterID: "Alter ID",
  UomGUID: "Base Unit GUID",
  UomName: "Base Unit Name",
  IsBatchOn: "Batch On",
  CategoryGUID: "Category GUID",
  CategoryName: "Category Name",
  CINNo: "CIN NO",
  RemoteCmpAddress: "Company Address",
  RemoteCmpBaseCurrency: "Company BaseCurrency",
  RemoteCmpBooksDate: "Company BooksDate",
  RemoteCmpCountry: "Company Country",
  RemoteCmpID: "Company ID",
  CompanyName: "Company Name",
  RemoteCmpName: "Company Name",
  RemoteCmpState: "Company State",
  Conversion: "Conversion",
  CostingMethod: "Costing Method",
  DecimalPlacesForPrinting: "Decimal Place For Printing",
  DecimalPlaces: "Decimal Places",
  DecimalSymbol: "Decimal Symbol",
  Denominator: "Denominator",
  Description: "Description",
  IsExpiryOn: "Expiry On",
  GSTNo: "GST NO",
  GUID: "GUID",
  MailingName: "Mailing Name",
  NameMasterID: "Master ID",
  MasterID: "Master ID",
  IsMfgOn: "MFG On",
  Name: "Name",
  OpeningBalance: "Opening Balance",
  OpeningRate: "Opening Rate",
  OpeningValue: "Opening Value",
  OriginalName: "Original Name",
  OrignalName: "Original Name",
  PANNo: "Pan No",
  ParentGUID: "Parent GUID",
  ParentName: "Parent Name",
  RemoteCmpPincode: "Rem Nincode",
  RemoteCmpEmail: "Rem NO",
  Remarks: "Remark",
  ReservedName: "Reserved Name",
  IsSimpleUnit: "Simple Unit",
  ID: "SNO",
  Autoincrement: "SNO",
  IsActive: "Status",
  ExpandedSymbol: "Symbol",
  CreatedBy: "Created By",
  ModifiedBy: "Modified By",
  CreatedDate: "Created Date",
  ModifiedDate: "Modified Date",
  CompanyID: "Company ID",
  DepartmentId: "Department ID",
  DepartmentName: "Department Name",
  CreatedOn: "Created On",
  ModifiedOn: "Modified On",
  DesignationId: "Designation Id",
  DesignationName: "Designation Name",
  EmployeeId: "Employee Id",
  EmployeeCode: "Employee Code",
  EmployeeName: "Employee Name",
  EmployeeType: "Employee Type",
  ReportingMgr: "Reporting Manager",
  Gender: "Gender",
  AddressLine1: "Address Line 1",
  AddressLine2: "Address Line 2",
  AddressLine3: "Address Line 3",
  PhoneNo: "Phone No",
  JoinDate: "Join Date",
  UserRoleId: "User Role Id",
  UserId: "User Id",
  RoleId: "Role Id",
  UserName: "User Name",
  UserType: "User Type",
  SettingId: "Setting Id",
  SettingName: "Setting Name",
};
