export const fieldsMap = {
  currency: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    MailingName: "Mailing Name",
    OriginalName: "Original Name",
    ExpandedSymbol: "Symbol",
    DecimalSymbol: "Decimal Symbol",
    DecimalPlaces: "Decimal Places",
    DecimalPlacesForPrinting: "Decimal Place For Printing",
    IsActive: "Status",
  },
  company: {
    RemoteCmpID: "Company ID",
    RemoteCmpName: "Company Name",
    RemoteCmpAddress: "Company Address",
    RemoteCmpCountry: "Company Country",
    RemoteCmpState: "Company State",
    RemoteCmpPincode: "Rem Nincode",
    RemoteCmpEmail: "Rem NO",
    RemoteCmpBaseCurrency: "Company BaseCurrency",
    RemoteCmpBooksDate: "Company BooksDate",
    GSTNo: "GST NO",
    CINNo: "CIN NO",
    PANNo: "Pan No",
    AdditionalField1: "Additional Field1",
    AdditionalField2: "Additional Field2",
    AdditionalField3: "Additional Field3",
    AdditionalField4: "Additional Field4",
    AdditionalField5: "Additional Field5",
    IsActive: "Status",
  },
  costCategory: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    IsActive: "Status",
  },
  costCenter: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    ParentName: "Parent Name",
    CategoryGUID: "Category GUID",
    CategoryName: "Category Name",
    IsActive: "Status",
  },
  group: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    ReservedName: "Reserve Name",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    ParentName: "Parent Name",
    AccountType: "Acount Type",
    IsActive: "Status",
  },
  stockCategory: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    IsActive: "Status",
  },
  stockGodown: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    IsActive: "Status",
  },
  stockGroup: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    IsActive: "Status",
  },
  stockUnit: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    IsSimpleUnit: "Simple Unit",
    DecimalPlaces: "Decimal Places",
    OrignalName: "Original Name",
    IsActive: "Status",
  },
  StockItem: {
    CompanyName: "Company Name",
    Name: "Name",
    MasterID: "Master ID",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    ParentName: "Parent Name",
    CategoryGUID: "Category GUID",
    CategoryName: "Category Name",
    Description: "Description",
    Remarks: "Remark",
    CostingMethod: "Costing Method",
    IsBatchOn: "Batch On ",
    IsMfgOn: "MFG On",
    IsExpiryOn: "Expiry On",
    UomGUID: "Base Unit GUID",
    UomName: "Base Unit Name",
    AltuomGUID: "Alt Unit GUID",
    AltuomName: "Alt Unit Name",
    Conversion: "Conversion",
    Denominator: "Denominator",
    OpeningBalance: "Opening Balance",
    OpeningValue: "Opening Value",
    OpeningRate: "Opening Rate",
    IsActive: "Status",
  },
  voucherType: {
    CompanyName: "Company Name",
    Name: "Name",
    NameMasterID: "Name Master ID",
    ReservedName: "Reserved Name",
    GUID: "GUID",
    AlterID: "Alter ID",
    ParentGUID: "Parent GUID",
    IsActive: "Status",
  },
  settingMaster: {
    SettingName: "Setting Name",
    SettingValue: "Setting Value ",
    Description: "Description",
    Status: "Status ",
    Created_ByUserName: "Created By",
    Created_Date: "Created On",
    Updated_ByUserName: "Updated By",
    UpdatedOn_Date: "Updated On",
  },
  designation: {
    DesignationCode: "Designation Code",
    DesignationName: "Designation Name",
    Status: "Staus",
    Created_ByUserName: "Created By",
    Created_Date: "Created On",
    Updated_ByUserName: "Updated By",
    UpdatedOn_Date: "Updated On",
  },
  departmentTable: {
    DepartmentCode: "Department Code",
    DepartmentName: "Department Name",
    Status: "Staus",
    Created_ByUserName: "Created By",
    Created_Date: "Created On",
    Updated_ByUserName: "Updated By",
    UpdatedOn_Date: "Updated On",
  },
  employeeTable: {
    EmployeeCode: "Employee Code",
    EmployeeName: "Employee Name",
    Mobile: "Mobile",
    Email: "Email ",
  },
  role: {
    RoleName: "Role Name",
  },
  User: {
    EmployeeId: "Employee Id",
    UserName: "User Name",
    UserType: "User Type",
    Description: "Description",
    Mobile: "Mobile",
    Email: "Email",
    Status: "Status",
  },
};
